export const EMOTIONS: string[] = [
  'Happiness',
  'Sadness',
  'Anger',
  'Fear',
  'Gratitude',
  'Hope',
  'Anxiety',
  'Patience',
  'Loneliness',
  'Stress',
  'Confusion',
  'Guilt',
  'Strength',
  'Forgiveness',
];